@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2MzE2NTQzODJ9.iKjjWnr0zoeemI1_XDvPvqrsq1-IZ5q57dSJvmg_slQ
@hostname = http://localhost:3000

### product Index
GET {{hostname}}/products?category=Pop
Authorization: Bearer {{jwt}}
Content-Type: application/json


### Product Show
GET {{hostname}}/products/6
### Product Create
POST {{hostname}}/products
Content-Type: application/json

{
  "name" : "Born Sinner",
  "price": 10,
  "image_url" : "https://upload.wikimedia.org/wikipedia/en/thumb/2/21/J_Cole_Born_Sinner1.jpg/220px-J_Cole_Born_Sinner1.jpg",
  "description": "J.Cole cd"
}
### Product Update
PATCH {{hostname}}/products/3
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "supplier_id" : "1"
}

### Product Delete
DELETE {{hostname}}/products/2

### users create (signup)
POST {{hostname}}/users
Content-Type: application/json

{
  "name" :"Jane Smith",
  "email": "J_S@gmail.com",
  "password": "password",
  "password_confirmation" : "password"
}

### sessions create (login)
POST {{hostname}}/sessions
Content-Type: application/json

{
  "email" : "J_S@gmail.com", 
  "password": "password"
}

### orders create
POST {{hostname}}/orders
Content-Type: application/json

Authorization: Bearer {{jwt}}
{
  
  "product_id" : 1, 
  "quantity": 1,
  "subtotal" : 7.99, 
  "tax": 0.99,
  "total" : 9.00

}

###orders show 
GET {{hostname}}/orders/1
Content-Type: application/json
Authorization: Bearer {{jwt}}

###orders index
GET {{hostname}}/orders
Content-Type: application/json
Authorization: Bearer {{jwt}}
