### Index
Get http://localhost:3000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzEyOTk4ODh9.0CTyltAJzqH_KUT_FuZUb6nvcjn46thLQFZbOPJazqI
Content-Type: application/json

### Show
GET http://localhost:3000/products/6
###
POST http://localhost:3000/products
Content-Type: application/json

{
  "name" : "Born Sinner",
  "price": 10,
  "image_url" : "https://upload.wikimedia.org/wikipedia/en/thumb/2/21/J_Cole_Born_Sinner1.jpg/220px-J_Cole_Born_Sinner1.jpg",
  "description": "J.Cole cd"
}
###
PATCH http://localhost:3000/products/3
Content-Type: application/json

{
  "supplier_id" : "2"
}

###
DELETE http://localhost:3000/products/2

### users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name" :"Johnny Doe",
  "email": "JD@gmail.com",
  "password": "password",
  "password_confirmation" : "password"
}

### sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email" : "JD@gmail.com", 
  "password": "password"
}

### orders create
POST http://localhost:3000/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzEzODgzNTF9.-Z-Xp7JswmBloZtHzAKv9Wszyl66TStBVfKqZ7R2q0c


{
  
  "product_id" : 1, 
  "quantity": 1,
  "subtotal" : 7.99, 
  "tax": 0.99,
  "total" : 9.00

}

###orders show 
GET http://localhost:3000/orders/1

###orders index
GET http://localhost:3000/orders