### product Index
GET  http://localhost:3000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzEyOTk4ODh9.0CTyltAJzqH_KUT_FuZUb6nvcjn46thLQFZbOPJazqI
Content-Type: application/json

### Product Show
GET http://localhost:3000/products/6
### Product Create
POST http://localhost:3000/products
Content-Type: application/json

{
  "name" : "Born Sinner",
  "price": 10,
  "image_url" : "https://upload.wikimedia.org/wikipedia/en/thumb/2/21/J_Cole_Born_Sinner1.jpg/220px-J_Cole_Born_Sinner1.jpg",
  "description": "J.Cole cd"
}
### Product Update
PATCH http://localhost:3000/products/3
Content-Type: application/json

{
  "supplier_id" : "2"
}

### Product Delete
DELETE http://localhost:3000/products/2

### users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name" :"Jane Smith",
  "email": "J_S@gmail.com",
  "password": "password",
  "password_confirmation" : "password"
}

### sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email" : "JD@gmail.com", 
  "password": "password"
}

### orders create
POST http://localhost:3000/orders
Content-Type: application/json

Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzE0OTA1ODd9.hpK9_EXZx1wDMMgMnGZcexpXMNAdb4p2SmZpS17gMKo
{
  
  "product_id" : 1, 
  "quantity": 1,
  "subtotal" : 7.99, 
  "tax": 0.99,
  "total" : 9.00

}

###orders show 
GET http://localhost:3000/orders/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzE0OTEwNDJ9.WHPh4g4U7kCgDyeR3OStQe1bOcE_n7XC9S5l7CyW1FA

###orders index
GET http://localhost:3000/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzE0OTM2ODV9.Te8PRnD3jHjO1qHh1PiBcyRRIrBkonF76hD_5h3QTyw
